/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as UnionStationAdminRouteImport } from './routes/union-station-admin'
import { Route as UnionStationRouteImport } from './routes/union-station'
import { Route as TenantsRouteImport } from './routes/tenants'
import { Route as SupportRouteImport } from './routes/support'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as MobileAppRouteImport } from './routes/mobile-app'
import { Route as MessagingRouteImport } from './routes/messaging'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as FacilitiesRouteImport } from './routes/facilities'
import { Route as EventsRouteImport } from './routes/events'
import { Route as CrmRouteImport } from './routes/crm'
import { Route as ContentRouteImport } from './routes/content'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as CafeRouteImport } from './routes/cafe'
import { Route as BookingsRouteImport } from './routes/bookings'
import { Route as BillingRouteImport } from './routes/billing'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AiAssistantRouteImport } from './routes/ai-assistant'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsRolesRouteImport } from './routes/settings.roles'
import { Route as CheckinCodeRouteImport } from './routes/checkin.$code'
import { Route as AuthVerifyEmailRouteImport } from './routes/auth.verify-email'
import { Route as AuthSsoRouteImport } from './routes/auth.sso'
import { Route as AuthSignUpRouteImport } from './routes/auth.sign-up'
import { Route as AuthSignInRouteImport } from './routes/auth.sign-in'
import { Route as AuthResetPasswordRouteImport } from './routes/auth.reset-password'
import { Route as AuthMfaRouteImport } from './routes/auth.mfa'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth.forgot-password'

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const UnionStationAdminRoute = UnionStationAdminRouteImport.update({
  id: '/union-station-admin',
  path: '/union-station-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const UnionStationRoute = UnionStationRouteImport.update({
  id: '/union-station',
  path: '/union-station',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantsRoute = TenantsRouteImport.update({
  id: '/tenants',
  path: '/tenants',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MobileAppRoute = MobileAppRouteImport.update({
  id: '/mobile-app',
  path: '/mobile-app',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagingRoute = MessagingRouteImport.update({
  id: '/messaging',
  path: '/messaging',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const FacilitiesRoute = FacilitiesRouteImport.update({
  id: '/facilities',
  path: '/facilities',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmRoute = CrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentRoute = ContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const CafeRoute = CafeRouteImport.update({
  id: '/cafe',
  path: '/cafe',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsRoute = BookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingRoute = BillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AiAssistantRoute = AiAssistantRouteImport.update({
  id: '/ai-assistant',
  path: '/ai-assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRolesRoute = SettingsRolesRouteImport.update({
  id: '/settings/roles',
  path: '/settings/roles',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckinCodeRoute = CheckinCodeRouteImport.update({
  id: '/checkin/$code',
  path: '/checkin/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthVerifyEmailRoute = AuthVerifyEmailRouteImport.update({
  id: '/auth/verify-email',
  path: '/auth/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSsoRoute = AuthSsoRouteImport.update({
  id: '/auth/sso',
  path: '/auth/sso',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/auth/sign-up',
  path: '/auth/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/auth/sign-in',
  path: '/auth/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthMfaRoute = AuthMfaRouteImport.update({
  id: '/auth/mfa',
  path: '/auth/mfa',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-assistant': typeof AiAssistantRoute
  '/analytics': typeof AnalyticsRoute
  '/billing': typeof BillingRoute
  '/bookings': typeof BookingsRoute
  '/cafe': typeof CafeRoute
  '/community': typeof CommunityRoute
  '/content': typeof ContentRoute
  '/crm': typeof CrmRoute
  '/events': typeof EventsRoute
  '/facilities': typeof FacilitiesRoute
  '/marketplace': typeof MarketplaceRoute
  '/messaging': typeof MessagingRoute
  '/mobile-app': typeof MobileAppRoute
  '/notifications': typeof NotificationsRoute
  '/support': typeof SupportRoute
  '/tenants': typeof TenantsRoute
  '/union-station': typeof UnionStationRoute
  '/union-station-admin': typeof UnionStationAdminRoute
  '/welcome': typeof WelcomeRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/mfa': typeof AuthMfaRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/auth/sso': typeof AuthSsoRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/checkin/$code': typeof CheckinCodeRoute
  '/settings/roles': typeof SettingsRolesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-assistant': typeof AiAssistantRoute
  '/analytics': typeof AnalyticsRoute
  '/billing': typeof BillingRoute
  '/bookings': typeof BookingsRoute
  '/cafe': typeof CafeRoute
  '/community': typeof CommunityRoute
  '/content': typeof ContentRoute
  '/crm': typeof CrmRoute
  '/events': typeof EventsRoute
  '/facilities': typeof FacilitiesRoute
  '/marketplace': typeof MarketplaceRoute
  '/messaging': typeof MessagingRoute
  '/mobile-app': typeof MobileAppRoute
  '/notifications': typeof NotificationsRoute
  '/support': typeof SupportRoute
  '/tenants': typeof TenantsRoute
  '/union-station': typeof UnionStationRoute
  '/union-station-admin': typeof UnionStationAdminRoute
  '/welcome': typeof WelcomeRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/mfa': typeof AuthMfaRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/auth/sso': typeof AuthSsoRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/checkin/$code': typeof CheckinCodeRoute
  '/settings/roles': typeof SettingsRolesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-assistant': typeof AiAssistantRoute
  '/analytics': typeof AnalyticsRoute
  '/billing': typeof BillingRoute
  '/bookings': typeof BookingsRoute
  '/cafe': typeof CafeRoute
  '/community': typeof CommunityRoute
  '/content': typeof ContentRoute
  '/crm': typeof CrmRoute
  '/events': typeof EventsRoute
  '/facilities': typeof FacilitiesRoute
  '/marketplace': typeof MarketplaceRoute
  '/messaging': typeof MessagingRoute
  '/mobile-app': typeof MobileAppRoute
  '/notifications': typeof NotificationsRoute
  '/support': typeof SupportRoute
  '/tenants': typeof TenantsRoute
  '/union-station': typeof UnionStationRoute
  '/union-station-admin': typeof UnionStationAdminRoute
  '/welcome': typeof WelcomeRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/mfa': typeof AuthMfaRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/auth/sso': typeof AuthSsoRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/checkin/$code': typeof CheckinCodeRoute
  '/settings/roles': typeof SettingsRolesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-assistant'
    | '/analytics'
    | '/billing'
    | '/bookings'
    | '/cafe'
    | '/community'
    | '/content'
    | '/crm'
    | '/events'
    | '/facilities'
    | '/marketplace'
    | '/messaging'
    | '/mobile-app'
    | '/notifications'
    | '/support'
    | '/tenants'
    | '/union-station'
    | '/union-station-admin'
    | '/welcome'
    | '/auth/forgot-password'
    | '/auth/mfa'
    | '/auth/reset-password'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/auth/sso'
    | '/auth/verify-email'
    | '/checkin/$code'
    | '/settings/roles'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-assistant'
    | '/analytics'
    | '/billing'
    | '/bookings'
    | '/cafe'
    | '/community'
    | '/content'
    | '/crm'
    | '/events'
    | '/facilities'
    | '/marketplace'
    | '/messaging'
    | '/mobile-app'
    | '/notifications'
    | '/support'
    | '/tenants'
    | '/union-station'
    | '/union-station-admin'
    | '/welcome'
    | '/auth/forgot-password'
    | '/auth/mfa'
    | '/auth/reset-password'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/auth/sso'
    | '/auth/verify-email'
    | '/checkin/$code'
    | '/settings/roles'
  id:
    | '__root__'
    | '/'
    | '/ai-assistant'
    | '/analytics'
    | '/billing'
    | '/bookings'
    | '/cafe'
    | '/community'
    | '/content'
    | '/crm'
    | '/events'
    | '/facilities'
    | '/marketplace'
    | '/messaging'
    | '/mobile-app'
    | '/notifications'
    | '/support'
    | '/tenants'
    | '/union-station'
    | '/union-station-admin'
    | '/welcome'
    | '/auth/forgot-password'
    | '/auth/mfa'
    | '/auth/reset-password'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/auth/sso'
    | '/auth/verify-email'
    | '/checkin/$code'
    | '/settings/roles'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiAssistantRoute: typeof AiAssistantRoute
  AnalyticsRoute: typeof AnalyticsRoute
  BillingRoute: typeof BillingRoute
  BookingsRoute: typeof BookingsRoute
  CafeRoute: typeof CafeRoute
  CommunityRoute: typeof CommunityRoute
  ContentRoute: typeof ContentRoute
  CrmRoute: typeof CrmRoute
  EventsRoute: typeof EventsRoute
  FacilitiesRoute: typeof FacilitiesRoute
  MarketplaceRoute: typeof MarketplaceRoute
  MessagingRoute: typeof MessagingRoute
  MobileAppRoute: typeof MobileAppRoute
  NotificationsRoute: typeof NotificationsRoute
  SupportRoute: typeof SupportRoute
  TenantsRoute: typeof TenantsRoute
  UnionStationRoute: typeof UnionStationRoute
  UnionStationAdminRoute: typeof UnionStationAdminRoute
  WelcomeRoute: typeof WelcomeRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthMfaRoute: typeof AuthMfaRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
  AuthSsoRoute: typeof AuthSsoRoute
  AuthVerifyEmailRoute: typeof AuthVerifyEmailRoute
  CheckinCodeRoute: typeof CheckinCodeRoute
  SettingsRolesRoute: typeof SettingsRolesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/union-station-admin': {
      id: '/union-station-admin'
      path: '/union-station-admin'
      fullPath: '/union-station-admin'
      preLoaderRoute: typeof UnionStationAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/union-station': {
      id: '/union-station'
      path: '/union-station'
      fullPath: '/union-station'
      preLoaderRoute: typeof UnionStationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenants': {
      id: '/tenants'
      path: '/tenants'
      fullPath: '/tenants'
      preLoaderRoute: typeof TenantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mobile-app': {
      id: '/mobile-app'
      path: '/mobile-app'
      fullPath: '/mobile-app'
      preLoaderRoute: typeof MobileAppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messaging': {
      id: '/messaging'
      path: '/messaging'
      fullPath: '/messaging'
      preLoaderRoute: typeof MessagingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/facilities': {
      id: '/facilities'
      path: '/facilities'
      fullPath: '/facilities'
      preLoaderRoute: typeof FacilitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm': {
      id: '/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof CrmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content': {
      id: '/content'
      path: '/content'
      fullPath: '/content'
      preLoaderRoute: typeof ContentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cafe': {
      id: '/cafe'
      path: '/cafe'
      fullPath: '/cafe'
      preLoaderRoute: typeof CafeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings': {
      id: '/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof BookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing': {
      id: '/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof BillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-assistant': {
      id: '/ai-assistant'
      path: '/ai-assistant'
      fullPath: '/ai-assistant'
      preLoaderRoute: typeof AiAssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/roles': {
      id: '/settings/roles'
      path: '/settings/roles'
      fullPath: '/settings/roles'
      preLoaderRoute: typeof SettingsRolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkin/$code': {
      id: '/checkin/$code'
      path: '/checkin/$code'
      fullPath: '/checkin/$code'
      preLoaderRoute: typeof CheckinCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/verify-email': {
      id: '/auth/verify-email'
      path: '/auth/verify-email'
      fullPath: '/auth/verify-email'
      preLoaderRoute: typeof AuthVerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sso': {
      id: '/auth/sso'
      path: '/auth/sso'
      fullPath: '/auth/sso'
      preLoaderRoute: typeof AuthSsoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-up': {
      id: '/auth/sign-up'
      path: '/auth/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/auth/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/mfa': {
      id: '/auth/mfa'
      path: '/auth/mfa'
      fullPath: '/auth/mfa'
      preLoaderRoute: typeof AuthMfaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiAssistantRoute: AiAssistantRoute,
  AnalyticsRoute: AnalyticsRoute,
  BillingRoute: BillingRoute,
  BookingsRoute: BookingsRoute,
  CafeRoute: CafeRoute,
  CommunityRoute: CommunityRoute,
  ContentRoute: ContentRoute,
  CrmRoute: CrmRoute,
  EventsRoute: EventsRoute,
  FacilitiesRoute: FacilitiesRoute,
  MarketplaceRoute: MarketplaceRoute,
  MessagingRoute: MessagingRoute,
  MobileAppRoute: MobileAppRoute,
  NotificationsRoute: NotificationsRoute,
  SupportRoute: SupportRoute,
  TenantsRoute: TenantsRoute,
  UnionStationRoute: UnionStationRoute,
  UnionStationAdminRoute: UnionStationAdminRoute,
  WelcomeRoute: WelcomeRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthMfaRoute: AuthMfaRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
  AuthSsoRoute: AuthSsoRoute,
  AuthVerifyEmailRoute: AuthVerifyEmailRoute,
  CheckinCodeRoute: CheckinCodeRoute,
  SettingsRolesRoute: SettingsRolesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
